[package]
name = "satoxid"
version = "0.1.2"
authors = ["neuring <neuring@pm.me>"]
edition = "2018"
license = "MIT"
description = "Boolean satisfiability problem encoding library written in rust."
repository = "https://github.com/neuring/satoxid"
readme = "README.md"
keywords = ["satisfiability", "sat", "sat-solver", "dimacs"]
categories = ["encoding"]

[dependencies]
ahash = "0.8.11"
cadical = { git = "https://github.com/sirandreww/cadical-rs", rev = "b65898198835223e6e5fb37004651f9aed3e15c8", optional = true  }
serde = { version = "1.0.126", features = ["derive"], optional = true }

[dev-dependencies]
num-integer = "0.1.44"
serde_json = "1.0.64"

#Used in examples.
itertools = "0.10.0"
structopt = "0.3.21"
anyhow = "1.0.40"
derive_more = "0.99.14"
strum = { version = "0.20.0", features = ["derive"] }

[features]
default = ["cadical"]
